---
argument_specs:
  main:
    short_description: An Ansible Role to create projects on Ansible gateway.
    options:
      aap_projects:
        description: Data structure describing your projects
        type: list
        required: true
        elements: dict
        options:
          allow_override:
            type: bool
            description: ['Allow changing the SCM branch or revision in a job template that uses this project.']
          copy_from:
            type: str
            description: ['Name or id to copy the project from.', 'This will copy an existing project and change any parameters supplied.', 'The new project name will be the one provided in the name parameter.', 'The organization parameter is not used in this, to facilitate copy from one organization to another.', 'Provide the id or use the lookup plugin to provide the id if multiple projects share the same name.']
          credential:
            type: str
            description: ['Name, ID, or named URL of the credential to use with this SCM resource.']
          custom_virtualenv:
            type: str
            description: ['Local absolute file path containing a custom Python virtualenv to use.', 'Only compatible with older versions of AWX/Tower', 'Deprecated, will be removed in the future']
          default_environment:
            type: str
            description: ['Default Execution Environment name, ID, or named URL to use for jobs relating to the project.']
          description:
            type: str
            description: ['Description to use for the project.']
          interval:
            default: 2
            required: False
            type: float
            description: ['The interval to request an update from the controller.', 'Requires wait.']
          local_path:
            type: str
            description: ['The server playbook directory for manual projects.']
          name:
            required: True
            type: str
            description: ['Name to use for the project.']
          new_name:
            type: str
            description: ['Setting this option will change the existing name (looked up via the name field.']
          notification_templates_error:
            type: list
            description: ['list of notifications to send on error']
          notification_templates_started:
            type: list
            description: ['list of notifications to send on start']
          notification_templates_success:
            type: list
            description: ['list of notifications to send on success']
          organization:
            type: str
            description: ['Name, ID, or named URL of organization for the project.']
          scm_branch:
            type: str
            description: ['The branch to use for the SCM resource.']
          scm_clean:
            type: bool
            description: ['Remove local modifications before updating.']
          scm_delete_on_update:
            type: bool
            description: ['Remove the repository completely before updating.']
          scm_refspec:
            type: str
            description: ['The refspec to use for the SCM resource.']
          scm_track_submodules:
            type: bool
            description: ['Track submodules latest commit on specified branch.']
          scm_type:
            type: str
            description: ['Type of SCM resource.']
          scm_update_cache_timeout:
            type: int
            description: ['Cache Timeout to cache prior project syncs for a certain number of seconds. Only valid if scm_update_on_launch is to True, otherwise ignored.']
          scm_update_on_launch:
            type: bool
            description: ['Perform an update to the local repository before launching a job with this project.']
          scm_url:
            type: str
            description: ['URL of SCM resource.']
          signature_validation_credential:
            type: str
            description: ['Name, ID, or named URL of the credential to use for signature validation.', 'If signature validation credential is provided, signature validation will be enabled.']
          state:
            default: present
            type: str
            description: ['Desired state of the resource.']
          timeout:
            type: int
            description: ['The amount of time (in seconds) to run before the SCM Update is canceled. A value of 0 means no timeout.', 'If waiting for the project to update this will abort after this amount of seconds']
          update_project:
            default: False
            type: bool
            description: ['Force project to update after changes.', 'Used in conjunction with wait, interval, and timeout.']
          wait:
            default: True
            type: bool
            description: ['Provides option (True by default) to wait for completed project sync before returning', 'Can assure playbook files are populated so that job templates that rely on the project may be successfully created']

      # Async variables
      projects_async_retries:
        default: "{{ aap_configuration_async_retries | default(30) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      aap_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      projects_async_delay:
        default: "{{ aap_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      aap_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.
      aap_configuration_async_dir:
        default:
        required: false
        description: Sets the directory to write the results file for async tasks. The default value is set to `null` which uses the Ansible Default of `/root/.ansible_async/`.

      # No_log variables
      gateway_projects_secure_logging:
        default: "{{ aap_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: Whether or not to include the sensitive tasks from this role in the log. Set this value to `true` if you will be providing your sensitive values from elsewhere.
      aap_configuration_secure_logging:
        default: false
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      platform_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      aap_hostname:
        default: None
        required: false
        description: URL to the Ansible gateway Server.
        type: str
      aap_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the Ansible gateway Server's SSL certificate.
        type: str
      aap_username:
        default: None
        required: false
        description: Admin User on the Ansible gateway Server. Either username / password or oauthtoken need to be specified.
        type: str
      aap_password:
        default: None
        required: false
        description: Gateway Admin User's password on the Ansible gateway Server. This should be stored in an Ansible Vault at vars/gateway-secrets.yml or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
      aap_token:
        default: None
        required: false
        description: Gateway Admin User's token on the Ansible gateway Server. This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
...
