---
- name: Include async status tasks
  ansible.builtin.include_tasks:
    file: "{{ __cas_task_file }}"
  loop: "{{ cas_task_files | default(__cas_default_task_files) }}"
  loop_control:
    loop_var: __cas_task_file
    label: "{{ __cas_task_file }}"
  vars:
    __cas_default_task_files:
      - collect_async_status.yml
      - handle_error.yml
...
