---
argument_specs:
  main:
    short_description: An Ansible Role to create event_streams on Ansible gateway.
    options:
      aap_event_streams:
        description: Data structure describing your event_streams
        type: list
        required: true
        elements: dict
        options:
          credential_name:
            type: str
            description: ['The name of the credential.', "The type of credential can only be one of ['HMAC Event Stream', 'Basic Event Stream', 'Token Event Stream', 'OAuth2 Event Stream', 'OAuth2 JWT Event Stream', 'ECDSA Event Stream', 'mTLS Event Stream', 'GitLab Event Stream', 'GitHub Event Stream', 'ServiceNow Event Stream', 'Dynatrace Event Stream']"]
          event_stream_type:
            type: str
            description: ['Type of the event stream.', 'This field is not necessary to create an event stream and will be ignored.', 'This field will be removed in version 3.0.0.']
          forward_events:
            default: False
            type: bool
            description: ['Enable the event stream to forward events to the rulebook activation where it is configured.']
          headers:
            default: 
            type: str
            description: ['Comma separated HTTP header keys that you want to include in the event payload. To include all headers in the event payload, leave the field empty.']
          name:
            required: True
            type: str
            description: ['Name of the event stream.']
          new_name:
            type: str
            description: ['Setting this option will change the existing name (lookup via name).']
          organization_name:
            type: str
            description: ['The name of the organization.']
          state:
            default: present
            type: str
            description: ['Desired state of the resource.']

      # Async variables
      event_streams_async_retries:
        default: "{{ aap_configuration_async_retries | default(30) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      aap_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      event_streams_async_delay:
        default: "{{ aap_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      aap_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.
      aap_configuration_async_dir:
        default:
        required: false
        description: Sets the directory to write the results file for async tasks. The default value is set to `null` which uses the Ansible Default of `/root/.ansible_async/`.

      # No_log variables
      gateway_event_streams_secure_logging:
        default: "{{ aap_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: Whether or not to include the sensitive tasks from this role in the log. Set this value to `true` if you will be providing your sensitive values from elsewhere.
      aap_configuration_secure_logging:
        default: false
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      platform_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      aap_hostname:
        default: None
        required: false
        description: URL to the Ansible gateway Server.
        type: str
      aap_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the Ansible gateway Server's SSL certificate.
        type: str
      aap_username:
        default: None
        required: false
        description: Admin User on the Ansible gateway Server. Either username / password or oauthtoken need to be specified.
        type: str
      aap_password:
        default: None
        required: false
        description: Gateway Admin User's password on the Ansible gateway Server. This should be stored in an Ansible Vault at vars/gateway-secrets.yml or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
      aap_token:
        default: None
        required: false
        description: Gateway Admin User's token on the Ansible gateway Server. This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
...
