---
argument_specs:
  main:
    short_description: An Ansible Role to create instances on Ansible gateway.
    options:
      aap_instances:
        description: Data structure describing your instances
        type: list
        required: true
        elements: dict
        options:
          capacity_adjustment:
            required: False
            type: float
            description: ['Capacity adjustment (0 <= capacity_adjustment <= 1)']
          enabled:
            required: False
            type: bool
            description: ['If true, the instance will be enabled and used.']
          hostname:
            required: True
            type: str
            description: ['Hostname of this instance.']
          listener_port:
            required: False
            type: int
            description: ['Port that Receptor will listen for incoming connections on.']
          managed_by_policy:
            required: False
            type: bool
            description: ['Managed by policy']
          node_state:
            required: False
            type: str
            description: ['Indicates the current life cycle stage of this instance.']
          node_type:
            required: False
            type: str
            description: ['Role that this node plays in the mesh.']
          peers:
            required: False
            type: list
            description: ['List of peers to connect outbound to. Only configurable for hop and execution nodes.', 'To remove all current peers, set value to an empty list, [].', 'Each item is an ID or address of a receptor address.', 'If item is address, it must be unique across all receptor addresses.']
          peers_from_control_nodes:
            required: False
            type: bool
            description: ['If enabled, control plane nodes will automatically peer to this node.']

      # Async variables
      instances_async_retries:
        default: "{{ aap_configuration_async_retries | default(30) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      aap_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      instances_async_delay:
        default: "{{ aap_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      aap_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.
      aap_configuration_async_dir:
        default:
        required: false
        description: Sets the directory to write the results file for async tasks. The default value is set to `null` which uses the Ansible Default of `/root/.ansible_async/`.

      # No_log variables
      gateway_instances_secure_logging:
        default: "{{ aap_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: Whether or not to include the sensitive tasks from this role in the log. Set this value to `true` if you will be providing your sensitive values from elsewhere.
      aap_configuration_secure_logging:
        default: false
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      platform_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      aap_hostname:
        default: None
        required: false
        description: URL to the Ansible gateway Server.
        type: str
      aap_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the Ansible gateway Server's SSL certificate.
        type: str
      aap_username:
        default: None
        required: false
        description: Admin User on the Ansible gateway Server. Either username / password or oauthtoken need to be specified.
        type: str
      aap_password:
        default: None
        required: false
        description: Gateway Admin User's password on the Ansible gateway Server. This should be stored in an Ansible Vault at vars/gateway-secrets.yml or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
      aap_token:
        default: None
        required: false
        description: Gateway Admin User's token on the Ansible gateway Server. This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
...
