---
argument_specs:
  main:
    short_description: An Ansible Role to create instance_groups on Ansible gateway.
    options:
      aap_instance_groups:
        description: Data structure describing your instance_groups
        type: list
        required: true
        elements: dict
        options:
          credential:
            required: False
            type: str
            description: ['Credential name, ID, or named URL to authenticate with Kubernetes or OpenShift.  Must be of type "OpenShift or Kubernetes API Bearer Token".']
          instances:
            required: False
            type: list
            description: ['The instance names, IDs, or named URLs associated with this instance_group']
          is_container_group:
            required: False
            type: bool
            description: ["Signifies that this InstanceGroup should act as a ContainerGroup. If no credential is specified, the underlying Pod's ServiceAccount will be used."]
          max_concurrent_jobs:
            required: False
            type: int
            description: ['Maximum number of concurrent jobs to run on this group. Zero means no limit.']
          max_forks:
            required: False
            type: int
            description: ['Max forks to execute on this group. Zero means no limit.']
          name:
            required: True
            type: str
            description: ['Name of this instance group.']
          new_name:
            type: str
            description: ['Setting this option will change the existing name (looked up via the name field.']
          pod_spec_override:
            required: False
            type: str
            description: ['A custom Kubernetes or OpenShift Pod specification.']
          policy_instance_list:
            required: False
            type: list
            description: ['List of exact-match Instances that will be assigned to this group']
          policy_instance_minimum:
            required: False
            type: int
            description: ['Static minimum number of Instances that will be automatically assign to this group when new instances come online.']
          policy_instance_percentage:
            required: False
            type: int
            description: ['Minimum percentage of all instances that will be automatically assigned to this group when new instances come online.']
          state:
            default: present
            type: str
            description: ['Desired state of the resource.']

      # Async variables
      instance_groups_async_retries:
        default: "{{ aap_configuration_async_retries | default(30) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      aap_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      instance_groups_async_delay:
        default: "{{ aap_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      aap_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.
      aap_configuration_async_dir:
        default:
        required: false
        description: Sets the directory to write the results file for async tasks. The default value is set to `null` which uses the Ansible Default of `/root/.ansible_async/`.

      # No_log variables
      gateway_instance_groups_secure_logging:
        default: "{{ aap_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: Whether or not to include the sensitive tasks from this role in the log. Set this value to `true` if you will be providing your sensitive values from elsewhere.
      aap_configuration_secure_logging:
        default: false
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      platform_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      aap_hostname:
        default: None
        required: false
        description: URL to the Ansible gateway Server.
        type: str
      aap_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the Ansible gateway Server's SSL certificate.
        type: str
      aap_username:
        default: None
        required: false
        description: Admin User on the Ansible gateway Server. Either username / password or oauthtoken need to be specified.
        type: str
      aap_password:
        default: None
        required: false
        description: Gateway Admin User's password on the Ansible gateway Server. This should be stored in an Ansible Vault at vars/gateway-secrets.yml or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
      aap_token:
        default: None
        required: false
        description: Gateway Admin User's token on the Ansible gateway Server. This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
...
