---
argument_specs:
  main:
    short_description: An Ansible Role to create schedules on Ansible gateway.
    options:
      aap_schedules:
        description: Data structure describing your schedules
        type: list
        required: true
        elements: dict
        options:
          credentials:
            type: list
            description: ['List of credential names, IDs, or named URLs applied as a prompt, assuming job template prompts for credentials']
          description:
            required: False
            type: str
            description: ['Optional description of this schedule.']
          diff_mode:
            required: False
            type: bool
            description: ['Enable diff mode for the job template.']
          enabled:
            required: False
            type: bool
            description: ['Enables processing of this schedule.']
          execution_environment:
            type: str
            description: ['Execution Environment name, ID, or named URL applied as a prompt, assuming job template prompts for execution environment']
          extra_data:
            required: False
            type: dict
            description: ['Specify C(extra_vars) for the template.']
          forks:
            type: int
            description: ['Forks applied as a prompt, assuming job template prompts for forks']
          instance_groups:
            type: list
            description: ['List of Instance Group names, IDs, or named URLs applied as a prompt, assuming job template prompts for instance groups']
          inventory:
            required: False
            type: str
            description: ['Inventory name, ID, or named URL applied as a prompt, assuming job template prompts for inventory']
          job_slice_count:
            type: int
            description: ['Job Slice Count applied as a prompt, assuming job template prompts for job slice count']
          job_tags:
            required: False
            type: str
            description: ['Comma separated list of the tags to use for the job template.']
          job_type:
            required: False
            type: str
            description: ['The job type to use for the job template.']
          labels:
            type: list
            description: ['List of labels applied as a prompt, assuming job template prompts for labels']
          limit:
            required: False
            type: str
            description: ['A host pattern to further constrain the list of hosts managed or affected by the playbook']
          name:
            required: True
            type: str
            description: ['Name of this schedule.']
          new_name:
            required: False
            type: str
            description: ['Setting this option will change the existing name (looked up via the name field.']
          organization:
            type: str
            description: ['The organization name, ID, or named URL the unified job template exists in.', 'Used for looking up the unified job template, not a direct model field.']
          rrule:
            required: False
            type: str
            description: ['A value representing the schedules iCal recurrence rule.', 'See rrule plugin for help constructing this value']
          scm_branch:
            required: False
            type: str
            description: ['Branch to use in job run. Project default used if blank. Only allowed if project allow_override field is set to true.']
          skip_tags:
            required: False
            type: str
            description: ['Comma separated list of the tags to skip for the job template.']
          state:
            default: present
            type: str
            description: ['Desired state of the resource.']
          timeout:
            type: int
            description: ['Timeout applied as a prompt, assuming job template prompts for timeout']
          unified_job_template:
            required: False
            type: str
            description: ['Name, ID, or named URL of unified job template to schedule. Used to look up an already existing schedule.']
          verbosity:
            required: False
            type: int
            description: ['Control the output level Ansible produces as the playbook runs. 0 - Normal, 1 - Verbose, 2 - More Verbose, 3 - Debug, 4 - Connection Debug.']

      # Async variables
      schedules_async_retries:
        default: "{{ aap_configuration_async_retries | default(30) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      aap_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      schedules_async_delay:
        default: "{{ aap_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      aap_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.
      aap_configuration_async_dir:
        default:
        required: false
        description: Sets the directory to write the results file for async tasks. The default value is set to `null` which uses the Ansible Default of `/root/.ansible_async/`.

      # No_log variables
      gateway_schedules_secure_logging:
        default: "{{ aap_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: Whether or not to include the sensitive tasks from this role in the log. Set this value to `true` if you will be providing your sensitive values from elsewhere.
      aap_configuration_secure_logging:
        default: false
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      platform_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      aap_hostname:
        default: None
        required: false
        description: URL to the Ansible gateway Server.
        type: str
      aap_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the Ansible gateway Server's SSL certificate.
        type: str
      aap_username:
        default: None
        required: false
        description: Admin User on the Ansible gateway Server. Either username / password or oauthtoken need to be specified.
        type: str
      aap_password:
        default: None
        required: false
        description: Gateway Admin User's password on the Ansible gateway Server. This should be stored in an Ansible Vault at vars/gateway-secrets.yml or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
      aap_token:
        default: None
        required: false
        description: Gateway Admin User's token on the Ansible gateway Server. This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
...
