---
argument_specs:
  main:
    short_description: An Ansible Role to create service_clusters on Ansible gateway.
    options:
      aap_service_clusters:
        description: Data structure describing your service_clusters
        type: list
        required: true
        elements: dict
        options:
          auth_type:
            type: str
            description: ['Authentication type for this service cluster', 'Defaults to JWT']
          dns_discovery_type:
            type: str
            description: ['DNS discovery type used for this service', 'STRICT_DNS (default) - Use, maintain and load balance among all returned addresses', 'LOGICAL_DNS - Use the first returned address at a time', 'See envoy documentation for further details']
          dns_lookup_family:
            type: str
            description: ['DNS address selection control', 'ALL - Use all addresses', 'AUTO - IPv6 preferred']
          health_check_healthy_threshold:
            type: int
            description: The number of consecutive successful health checks before a node is considered healthy.
          health_check_interval_seconds:
            type: int
            description: The time between health check requests.
          health_check_timeout_seconds:
            type: int
            description: The time to wait for a health check to complete.
          health_check_unhealthy_threshold:
            type: int
            description: The number of consecutive failed health checks before a node is considered unhealthy.
          health_checks_enabled:
            type: bool
            description: If true, health checks will be used to determine if a node is healthy.
          healthy_panic_threshold:
            type: int
            description: The percentage of failed hosts when the proxy will panic and start routing traffic to all nodes. Set to 0 to disable this.
          name:
            required: True
            type: str
            description: The name of the AAP Service, must be unique
          new_name:
            type: str
            description: Setting this option will change the existing name (looked up via the name field)
          outlier_detection_base_ejection_time_seconds:
            type: int
            description: The base time a node will be ejected for.
          outlier_detection_consecutive_5xx:
            type: int
            description: Number of consecutive 5xx responses to consider a node unhealthy.
          outlier_detection_enabled:
            type: bool
            description: If true, outlier detection will be used to determine if a node is unhealthy and should be ejected from the cluster.
          outlier_detection_interval_seconds:
            type: int
            description: The time interval between ejection analysis sweeps.
          outlier_detection_max_ejection_percent:
            type: int
            description: The maximum percent of nodes that can be ejected from the cluster.
          service_type:
            type: str
            description: ['Service Type for this cluster - name or ID', 'Required when creating new Service Cluster']
          upstream_hostname:
            type: str
            description: If set, Server Name Identification(SNI) and host header are set to this value

      # Async variables
      service_clusters_async_retries:
        default: "{{ aap_configuration_async_retries | default(30) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      aap_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      service_clusters_async_delay:
        default: "{{ aap_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      aap_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.
      aap_configuration_async_dir:
        default:
        required: false
        description: Sets the directory to write the results file for async tasks. The default value is set to `null` which uses the Ansible Default of `/root/.ansible_async/`.

      # No_log variables
      gateway_service_clusters_secure_logging:
        default: "{{ aap_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: Whether or not to include the sensitive tasks from this role in the log. Set this value to `true` if you will be providing your sensitive values from elsewhere.
      aap_configuration_secure_logging:
        default: false
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      platform_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      aap_hostname:
        default: None
        required: false
        description: URL to the Ansible gateway Server.
        type: str
      aap_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the Ansible gateway Server's SSL certificate.
        type: str
      aap_username:
        default: None
        required: false
        description: Admin User on the Ansible gateway Server. Either username / password or oauthtoken need to be specified.
        type: str
      aap_password:
        default: None
        required: false
        description: Gateway Admin User's password on the Ansible gateway Server. This should be stored in an Ansible Vault at vars/gateway-secrets.yml or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
      aap_token:
        default: None
        required: false
        description: Gateway Admin User's token on the Ansible gateway Server. This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
...
