---
argument_specs:
  main:
    short_description: An Ansible Role to create inventory_sources on Ansible gateway.
    options:
      aap_inventory_sources:
        description: Data structure describing your inventory_sources
        type: list
        required: true
        elements: dict
        options:
          credential:
            type: str
            description: ['Credential name, ID, or named URL to use for the source.']
          custom_virtualenv:
            type: str
            description: ['Local absolute file path containing a custom Python virtualenv to use.', 'Only compatible with older versions of AWX/Controller', 'Deprecated, will be removed in the future']
          description:
            type: str
            description: ['The description to use for the inventory source.']
          enabled_value:
            type: str
            description: ['Value when the host is considered enabled, e.g., "powered_on"']
          enabled_var:
            type: str
            description: ['The variable to use to determine enabled state e.g., "status.power_state"']
          execution_environment:
            type: str
            description: ['Execution Environment name, ID, or named URL to use for the source.']
          host_filter:
            type: str
            description: ['If specified, AWX will only import hosts that match this regular expression.']
          inventory:
            required: True
            type: str
            description: ['Inventory name, ID, or named URL the group should be made a member of.']
          limit:
            type: str
            description: ['Enter host, group or pattern match']
          name:
            required: True
            type: str
            description: ['The name to use for the inventory source.']
          new_name:
            type: str
            description: ['A new name for this assets (will rename the asset)']
          notification_templates_error:
            type: list
            description: ['list of notifications to send on error']
          notification_templates_started:
            type: list
            description: ['list of notifications to send on start']
          notification_templates_success:
            type: list
            description: ['list of notifications to send on success']
          organization:
            type: str
            description: ["Name of the inventory source's inventory's organization."]
          overwrite:
            type: bool
            description: ['Delete child groups and hosts not found in source.']
          overwrite_vars:
            type: bool
            description: ['Override vars in child groups and hosts with those from external source.']
          scm_branch:
            type: str
            description: ['Inventory source SCM branch.', 'Project must have branch override enabled.']
          source:
            type: str
            description: ['The source to use for this group.']
          source_path:
            type: str
            description: ['For an SCM based inventory source, the source path points to the file within the repo to use as an inventory.']
          source_project:
            type: str
            description: ['Project name, ID, or named URL to use as source with scm option']
          source_vars:
            type: dict
            description: ['The variables or environment fields to apply to this source type.']
          state:
            default: present
            type: str
            description: ['Desired state of the resource.']
          timeout:
            type: int
            description: The amount of time (in seconds) to run before the task is canceled.
          update_cache_timeout:
            type: int
            description: ['Time in seconds to consider an inventory sync to be current.']
          update_on_launch:
            type: bool
            description: ['Refresh inventory data from its source each time a job is run.']
          verbosity:
            type: int
            description: The verbosity level to run this inventory source under.

      # Async variables
      inventory_sources_async_retries:
        default: "{{ aap_configuration_async_retries | default(30) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      aap_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      inventory_sources_async_delay:
        default: "{{ aap_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      aap_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.
      aap_configuration_async_dir:
        default:
        required: false
        description: Sets the directory to write the results file for async tasks. The default value is set to `null` which uses the Ansible Default of `/root/.ansible_async/`.

      # No_log variables
      gateway_inventory_sources_secure_logging:
        default: "{{ aap_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: Whether or not to include the sensitive tasks from this role in the log. Set this value to `true` if you will be providing your sensitive values from elsewhere.
      aap_configuration_secure_logging:
        default: false
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      platform_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      aap_hostname:
        default: None
        required: false
        description: URL to the Ansible gateway Server.
        type: str
      aap_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the Ansible gateway Server's SSL certificate.
        type: str
      aap_username:
        default: None
        required: false
        description: Admin User on the Ansible gateway Server. Either username / password or oauthtoken need to be specified.
        type: str
      aap_password:
        default: None
        required: false
        description: Gateway Admin User's password on the Ansible gateway Server. This should be stored in an Ansible Vault at vars/gateway-secrets.yml or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
      aap_token:
        default: None
        required: false
        description: Gateway Admin User's token on the Ansible gateway Server. This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
...
