---
argument_specs:
  main:
    short_description: An Ansible Role to create inventories on Ansible gateway.
    options:
      aap_inventories:
        description: Data structure describing your inventories
        type: list
        required: true
        elements: dict
        options:
          copy_from:
            type: str
            description: ['Name or id to copy the inventory from.', 'This will copy an existing inventory and change any parameters supplied.', 'The new inventory name will be the one provided in the name parameter.', 'The organization parameter is not used in this, to facilitate copy from one organization to another.', 'Provide the id or use the lookup plugin to provide the id if multiple inventories share the same name.']
          description:
            type: str
            description: ['The description to use for the inventory.']
          host_filter:
            type: str
            description: ['The host_filter field. Only useful when C(kind=smart).']
          input_inventories:
            type: list
            description: ['List of Inventory names, IDs, or named URLs to use as input for Constructed Inventory.']
          instance_groups:
            type: list
            description: ['list of Instance Group names, IDs, or named URLs for this Organization to run on.']
          kind:
            type: str
            description: ['The kind field. Cannot be modified after created.']
          name:
            required: True
            type: str
            description: ['The name to use for the inventory.']
          new_name:
            type: str
            description: ['Setting this option will change the existing name (looked up via the name field.']
          organization:
            required: True
            type: str
            description: ['Organization name, ID, or named URL the inventory belongs to.']
          prevent_instance_group_fallback:
            type: bool
            description: ['Prevent falling back to instance groups set on the organization']
          state:
            default: present
            type: str
            description: ['Desired state of the resource.']
          variables:
            type: dict
            description: ['Inventory variables.']

      # Async variables
      inventories_async_retries:
        default: "{{ aap_configuration_async_retries | default(30) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      aap_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      inventories_async_delay:
        default: "{{ aap_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      aap_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.
      aap_configuration_async_dir:
        default:
        required: false
        description: Sets the directory to write the results file for async tasks. The default value is set to `null` which uses the Ansible Default of `/root/.ansible_async/`.

      # No_log variables
      gateway_inventories_secure_logging:
        default: "{{ aap_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: Whether or not to include the sensitive tasks from this role in the log. Set this value to `true` if you will be providing your sensitive values from elsewhere.
      aap_configuration_secure_logging:
        default: false
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      platform_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      aap_hostname:
        default: None
        required: false
        description: URL to the Ansible gateway Server.
        type: str
      aap_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the Ansible gateway Server's SSL certificate.
        type: str
      aap_username:
        default: None
        required: false
        description: Admin User on the Ansible gateway Server. Either username / password or oauthtoken need to be specified.
        type: str
      aap_password:
        default: None
        required: false
        description: Gateway Admin User's password on the Ansible gateway Server. This should be stored in an Ansible Vault at vars/gateway-secrets.yml or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
      aap_token:
        default: None
        required: false
        description: Gateway Admin User's token on the Ansible gateway Server. This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
...
